# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 547597a863a8096ca37fe43eedb914f2833d9279db055c79ddd5d7e5a5042f4a26405e1b8bbe80744283593fda112d9a558ee1a73b59589a967f19649ca70a31

test:
  secret_key_base: e1947b054607b9df07a11377784b95f6efe441392b39dbef0bf3b4c1a9a2e89e24a31db77d55a16da331700c2869535be75634783a5ad14f705b062af1147523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
